### ISSUE TITLE
Waterfall foam transparency broken

### ISSUE THREAD

**Issue by kaucukovnik** [kirides/GD3D11#95] opened 2022-01-02 10:29 UTC
G1 Waterfall foam displays water surface instead of transparency. This is a long lasting and pretty major visual bug, yet I can find barely any mention of it anywhere. I even looked up a DX11 Gothic video from 2018 to make sure me or my PC isn't going crazy and the bug was there.
I did some searching in the source files and found a water texture alpha check to specifically exclude water foam. Unfortunately builds from before and after show no change whatsoever in game. Gothic Reloaded demo from 2017 has the same issue as well. No renderer setting (F11, Ctrl+F11) has any effect either.

**Comment by kirides** [comment] 2022-01-02 10:40
Are you talking about this issue perhaps?

https://github.com/kirides/GD3D11/issues/6

**Comment by kaucukovnik** [comment] 2022-01-02 11:22
Crap. Sorry for creating a duplicate.
So it's a well known "at least it's just Gothic 1" fon'tfix/unfixable issue? It makes the entire renderer pointless for G1, and any other visual improvements only make the bug stand out more. But we have wetness and tesselation, yay! Wierd priorities...
/rant

**Comment by kirides** [comment] 2022-01-02 11:59
> So it's a well known "at least it's just Gothic 1" fon'tfix/unfixable issue?
What makes you think the issue is a "won't fix" or "unfixable"?
Nobody tackled this problem yet. G1 makes up a really, *really* low amount of all gothic players and available mods.
It's also very different in a few engine/rendering aspects to G2.

> But we have wetness and tesselation, yay! Wierd priorities...
> /rant
Gothic 1 was always an afterthought of this renderer since it's inception.  
The original developer didn't know / care enough about G1 and currently no other dev who knows enough about dx11 *and* G1 rendering raised his hand to pickup the job to implement G1 specific stuff.

wetness and tesselation work "fine" in G2, as almost anything.
Does somebody here still remember the "G1 teleport crash" or "random blackscreen" issues that made G1 unplayable with the renderer? Somebody tackled to issues and fixed them. They don't exist anymore.

**Closed by kirides** 2022-01-02 11:59 UTC

**Comment by kaucukovnik** [comment] 2022-01-03 18:29
> What makes you think the issue is a "won't fix" or "unfixable"?
Maybe the fact that the last reply, mentioning engine limitations, is 2 years old, and the immensely more popular G2 doesn't suffer from the bug? Maybe the fact it's actually one of the oldest bug reports here?
Oh well, I'm not here to argue. Wanted to point out a serious bug, found out it's well known already. Kind of sad seeing all those guides from Reddit to Steam and Gog recomending the renderer as totally the best way to play the game. Maybe they all just pimp the game up, take screenshots from the initial bridge ("look at the draw distance, guys!") and no one actually plays? It's a mystery to me.

The file naming of "GD3D11..." and "Gothic2-GD3D11..." is even more confusing, makes it look like the original Gothic is the main project (thus GD3D11) and the sequel is the afterthought ("Gothic2-" put in front of the "regular" name). 

I'd recommend making this clear somewhere visible. Call it a beta or something, this is not in release state - proper transparency handling is basic functionality for a VISUAL enhancement.
I'm not trying to knock your project down, just suggesting a way to manage expectations so that you don't get more posts like this. I wouldn't have been this abrassive if the entire internet didn't hype the whole thing the way it did.

**Comment by kirides** [comment] 2022-01-03 18:37
> The file naming of "GD3D11..." and "Gothic2-GD3D11..." is even more confusing, makes it look like the original Gothic is the main project (thus GD3D11) and the sequel is the afterthought ("Gothic2-" put in front of the "regular" name).

I should definetly *remove* Gothic2 fron the front and put **SpacerNET** there as that build is a special build, as noted by the extension "_SpacerNET"

Also, if this is "literally unplayable" for you. Then just don't play with it?

There are a *lot* of people who can't even play G1/G2 *without* the renderer anymore because of technical issues that arise from having Nivida Optimus Notebooks or other hardware combinations (e.g. many issues in the past with AMD RX 5700 XT)

I'll make sure that the readme will mention a big red flag for G1 as it's unplayable with kinda broken transparency on a few textures...

**Comment by kaucukovnik** [comment] 2022-01-03 19:38
> Also, if this is "literally unplayable" for you. Then just don't play with it?

I never said that. I said it defeated the purpose of installing a visual enhancement.

>  with kinda broken transparency on a few textures...

No. Mention visually ruined waterfalls and faulty foliage. That doesn't sound so insignificant, eh?

Or just start arguing the exact meaning of "ruined" now. Whatever. I'm done here.
